version: '3.9'
services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'details'
    ports:
      - 5431:5432
    volumes:
      - /pg-data:/var/lib/postgresql/data
